# Generated by Django 2.1.1 on 2018-10-01 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('F', 'Física'), ('J', 'Jurítica')], max_length=1)),
                ('cpfcnpj', models.CharField(max_length=14)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=800)),
                ('cep', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=6)),
                ('estado', models.CharField(max_length=2)),
                ('ibge', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=80)),
                ('observacao', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
